### ISSUE TITLE
uninitialized constant KbArticle

### ISSUE THREAD

**Issue by mooreaa** [peclik/clipboard_image_paste#43]
Installed in 3.0.1 and ran rake:

NameError: uninitialized constant KbArticle

/usr/share/redmine-3.0.1/plugins/clipboard_image_paste-1.9/lib/clipboard_image_paste/attachment_patch.rb:130:in `<top (required)>'
/usr/share/redmine-3.0.1/plugins/clipboard_image_paste-1.9/init.rb:33:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:in `instance_exec'
/var/lib/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/var/lib/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:189:in `call'
/var/lib/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:189:in `block in simple'
/var/lib/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
/var/lib/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
/var/lib/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
/var/lib/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/var/lib/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_prepare_callbacks'
/var/lib/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/1.9.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/var/lib/gems/1.9.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/var/lib/gems/1.9.1/gems/railties-4.2.0/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/var/lib/gems/1.9.1/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/1.9.1/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/1.9.1/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/1.9.1/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/1.9.1/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
/usr/share/redmine-3.0.1/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/1.9.1/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
/var/lib/gems/1.9.1/gems/railties-4.2.0/lib/rails/application.rb:443:in `block in run_tasks_blocks'
Tasks: TOP => redmine:plugins:migrate => environment

**Comment by peclik** [comment]
This should be already fixed in 1.10.

**Comment by steph-ben** [comment]
I ran into the same issue.

You should really update the link in the main github page, because I think a lot of people still download the 1.9 version !
