### ISSUE TITLE
Cant insert image 

### ISSUE THREAD

**Issue by KirillB09** [peclik/clipboard_image_paste#44]
We've updated version of Redmine from 2.5 to 3.0.2 and updated this plugin from version 1,8 to 1.10.
Link to plugin is available from new issue but now i cant insert immage with ctrl-v 

![image](https://cloud.githubusercontent.com/assets/12407938/7582892/375bf7ba-f89a-11e4-9a6d-5531508a0ff7.png)

![image](https://cloud.githubusercontent.com/assets/12407938/7582829/e2346ec0-f899-11e4-84f3-cb44d3656db5.png)

NB 
while using IE 11 i still have error message 
![image](https://cloud.githubusercontent.com/assets/12407938/7582938/866380da-f89a-11e4-8123-4df49b884be4.png)

**Comment by peclik** [comment]
I've just checked Redmine 3.0.3, Chrome 42, Firefox 36. Everything works fine.
Do you insert images put into clipboard with PrintScr?
Check JavaScript console (Ctrl+Shift+J) for errors during page loading and image pasting.
Try disabling other plugins (there can be some conflict between).
I will check IE 11 later (probably you have some web page compatibility setting for your Redmine server).

**Comment by KirillB09** [comment]
Hi
yes i used chrome version 42. I puted image into clipbord using PrintScr and Alt+PrintScr. We don't have any other plug-in , only yours -)
Here is message from console 
![image](https://cloud.githubusercontent.com/assets/12407938/7587355/4be1d438-f8be-11e4-96e3-0a6117553ca8.png)

**Comment by peclik** [comment]
Your browser is somehow using old files (there is no jcrop-0.9.10 in plugin now). Try delete redmine/public/plugin_assets/clipboard_image_paste and restart web server.

**Comment by peclik** [comment]
Did you even restarted the server after plugin update? Invalid reference to old jcrop must be in some cached html page.

**Comment by KirillB09** [comment]
Worm  thanks. now it's ok
