### ISSUE TITLE
broken with FF 39

### ISSUE THREAD

**Issue by markschultz** [peclik/clipboard_image_paste#46]
probably related to #31.
I get the following error in the console when I click "OK"
`SecurityError: The operation is insecure.`
line 539 which is the following `return dst.toDataURL("image/png");`

I also found this which might explain the issue: http://stackoverflow.com/questions/29133612/securityerror-the-operation-is-insecure-in-canvas-todataurl

**Comment by TrurlMcByte** [comment]
same "SecurityError: The operation is insecure."
in https://github.com/peclik/clipboard_image_paste/blob/master/assets/javascripts/clipboard_image_paste.js#L539

**Comment by TrurlMcByte** [comment]
pull https://github.com/peclik/clipboard_image_paste/pull/49 fixing it

**Comment by peclik** [comment]
Duplicate in #64. #49 doesn't fix that.

**Comment by markschultz** [comment]
according to the SO post above the pr #49 may indeed fix this and #64. Has it been tested?

**Comment by peclik** [comment]
Yes I've tried that without success.
