### ISSUE TITLE
fresh install with redmine 3.0 ... kbarticle error on migrate

### ISSUE THREAD

**Issue by mvording** [peclik/clipboard_image_paste#48]
Hello:

I tried installing the plugin with redmine 3.0,   and the migrate script fails on a line expecting "kbarticle" to exist, however I do not have the knowledge base plugin installed.

$ rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NameError: uninitialized constant KbArticle
/var/data/redmine/plugins/clipboard_image_paste/lib/clipboard_image_paste/attachment_patch.rb:130:in `<top (required)>'
/var/data/redmine/plugins/clipboard_image_paste/init.rb:33:in`block in <top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:444:in `instance_exec'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:444:in`block in make_lambda'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:190:in `call'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:190:in`block in simple'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `call'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in`block in call'

**Comment by peclik** [comment]
Hi, 
probably you don't have last version 1.10 installed, then restart http server.

**Comment by FredP34** [comment]
Hi,
I tried to install the version 1.9 of the plugin with redmine 3.0.4 and I get the same NameError (uninitialized constant KbArticle). 
How can I download the last version 1.10 please ?
Thank you

**Comment by peclik** [comment]
Hi,
download link: https://github.com/peclik/clipboard_image_paste/archive/v1.10.zip
After unzipping rename clipboard_image_paste-1.10 folder to clipboard_image_paste to be placed under Redmine's plugins folder.

**Comment by delatbabel** [comment]
Your README.textile file points people at v1.9 which is why people keep raising this issue.
