### ISSUE TITLE
Import image vom "greenshot"

### ISSUE THREAD

**Issue by cbuczek** [peclik/clipboard_image_paste#52]
Hi there,

its a llitle bit strange, but I can´t paste images from greenshot (getgreenshot.org) directly into this plugin. Everytime the message "Die Zwischenablage enthält kein Bild. Drücken Sie die Druck-Taste erneut" (means: there is not image; please press the print-key) pops up.
when I paste an image from greenshot to word -> copy the image in word an paste it into plugin: It works.

Has anyone an idea, what is going wrong between greenshot and this plugin?

edit: 
additional to the problem with images from greenshot: the same failure comes by copy´n´paste images from mail (MS Outlook) :-/

Regard 
Christian Buczek

**Comment by peclik** [comment]
Probably CORS rules applied, same as #64.
