### ISSUE TITLE
doesnt work with redmine 3.2

### ISSUE THREAD

**Issue by jeacott** [peclik/clipboard_image_paste#55]
doesnt work with redmine 3.2
any plans to update?

thanks

**Comment by atmosx** [comment]
Confirmed.

**Comment by kocio-pl** [comment]
However it works with 3.1.3, so "3.1.x" can be added to Compatibility section.

**Comment by jeacott1** [comment]
the error is reported like this:

Processing by AdminController#index as HTML
  Current user: admin (id=1)
  Rendered admin/_menu.html.erb (14.1ms)
  Rendered admin/index.html.erb within layouts/admin (209.8ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (1.1ms)
  Rendered plugins/redmine_wiki_extensions/app/views/wiki_extensions/_html_header.html.erb (1.2ms)
  Rendered layouts/base.html.erb (387.8ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (1.3ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (0.1ms)
  Rendered plugins/redmine_wiki_extensions/app/views/wiki_extensions/_html_header.html.erb (0.1ms)
Completed 500 Internal Server Error in 793ms (ActiveRecord: 8.0ms)

ActionView::Template::Error (Missing partial clipboard_image_paste/_headers with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :rsb]}. Searched in:
  * "/srv/redmine/plugins/redmine_wiki_extensions/app/views"
  * "/srv/redmine/plugins/redmine_code_review/app/views"
  * "/srv/redmine/app/views"
):
    11: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    12: <%= javascript_heads %>
    13: <%= heads_for_theme %>
    14: <%= call_hook :view_layouts_base_html_head %>
    15: 
    16: <%= yield :header_tags -%>
    17: </head>
  lib/redmine/hook.rb:119:in `block (2 levels) in render_on'
  lib/redmine/hook.rb:117:in `map'
  lib/redmine/hook.rb:117:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:167:in `call_hook'
  app/views/layouts/base.html.erb:14:in `_app_views_layouts_base_html_erb__3533796493559235108_46353740'
  app/controllers/application_controller.rb:469:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:467:in `render_error'
  app/controllers/application_controller.rb:455:in `render_404'
  app/controllers/application_controller.rb:479:in `missing_template'


any thoughts on how easy this might be to fix?

**Comment by LeGiangAnh** [comment]
@jeacott how can?

**Comment by onurozgurozkan** [comment]
Doesn't work on Redmine 3.2.1.stable. I use 

- OSX El Capitan
- Chrome Version 49.0.2623.110 (64-bit)

Redmine Environment:
  Redmine version             3.2.1.stable
  Ruby version                   2.2.3-p173 (2015-08-18) [x86_64-linux]
  Rails version                   4.2.5.2
  Environment                    production            
Redmine plugins:
  clipboard_image_paste          1.10

@jeacott how can?

**Comment by Nuranto** [comment]
@jeacott1

**Comment by jeacott** [comment]
just rename the folder properly and it works. but it kinda interferes with the drag/drop thats built into redmine now so I'm not using it anyway.

**Comment by romanr** [comment]
renamed to what? the folder name is "clipboard_image_paste" and it's not working.

**Comment by jeacott1** [comment]
@romanr mine was not named plugins/clipboard_image_paste, 
and renaming it to 'clipboard_image_paste'made it work.

**Comment by yukihane** [comment]
[v1.10](https://github.com/peclik/clipboard_image_paste/releases) works well for me.

**Comment by clems94** [comment]
Hello it does not wrok for me redmine 3.2.6 ruby v2.3.4

**Comment by peclik** [comment]
Provide more info: what does/doesn't work, symptoms, logs, javascript console log...
