### ISSUE TITLE
Problems with Redmine 2.5.2 

### ISSUE THREAD

**Issue by HandsomeRob2016** [peclik/clipboard_image_paste#59]
I´m running Redmine on debian-jessie. Installation via [apt-get](https://wiki.debian.org/redmine).

> Environment:
>   Redmine version                2.5.2.devel
>   Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
>   Rails version                  4.1.8
>   Environment                    production
>   Database adapter               Mysql2
> SCM:
>   Subversion                     1.8.10
>   Filesystem  
> Redmine plugins:
>   clipboard_image_paste          1.10

I did the following:
1. Create folder "/usr/share/redmine/plugins" 
2. unzip the 1.10 plugin to it
3. restart apache

Now i got the same behavior like [here ](https://github.com/peclik/clipboard_image_paste/issues/37). (Button showed at the bottom)
After clicking IE 11 Debugger says object doesnt support the method _cbImagePaste.showPasteDialog()_

Did I forgot something?

**Comment by peclik** [comment]
Can you, please, list directories in /usr/share/redmine/plugins?

**Comment by HandsomeRob2016** [comment]
> .:
> insgesamt 4
> drwxr-xr-x 7 root root 4096 Jul 13 08:57 clipboard_image_paste
> 
> ./clipboard_image_paste:
> insgesamt 32
> drwxr-xr-x 3 root root 4096 Jul 13 08:57 app
> drwxr-xr-x 4 root root 4096 Jul 13 08:57 assets
> drwxr-xr-x 3 root root 4096 Jul 13 08:57 config
> -rw-r--r-- 1 root root 1349 Jul 13 08:59 init.rb
> drwxr-xr-x 3 root root 4096 Jul 13 08:57 lib
> -rw-r--r-- 1 root root 5964 Jul 13 08:59 README.textile
> drwxr-xr-x 2 root root 4096 Jul 13 08:57 suppl
> 
> ./clipboard_image_paste/app:
> insgesamt 4
> drwxr-xr-x 3 root root 4096 Jul 13 08:57 views
> 
> ./clipboard_image_paste/app/views:
> insgesamt 4
> drwxr-xr-x 2 root root 4096 Jul 13 08:57 clipboard_image_paste
> 
> ./clipboard_image_paste/app/views/clipboard_image_paste:
> insgesamt 12
> -rw-r--r-- 1 root root 4322 Jul 13 08:59 _add_form.html.erb
> -rw-r--r-- 1 root root 1005 Jul 13 08:59 _headers.html.erb
> 
> ./clipboard_image_paste/assets:
> insgesamt 8
> drwxr-xr-x 2 root root 4096 Jul 13 08:57 javascripts
> drwxr-xr-x 3 root root 4096 Jul 13 08:57 stylesheets
> 
> ./clipboard_image_paste/assets/javascripts:
> insgesamt 412
> -rw-r--r-- 1 root root  18502 Jul 13 08:59 clipboard_image_paste.js
> -rw-r--r-- 1 root root  42746 Jul 13 08:59 jcrop-0.9.12-p1.js
> -rw-r--r-- 1 root root  16225 Jul 13 08:59 jcrop-0.9.12-p1.min.js
> -rw-r--r-- 1 root root  94840 Jul 13 08:59 jquery-1.7.2.min.js
> -rw-r--r-- 1 root root 237802 Jul 13 08:59 jquery-ui-1.9.2.min.js
> 
> ./clipboard_image_paste/assets/stylesheets:
> insgesamt 44
> -rw-r--r-- 1 root root  1367 Jul 13 08:59 clipboard_image_paste.css
> drwxr-xr-x 2 root root  4096 Jul 13 08:57 images
> -rw-r--r-- 1 root root   329 Jul 13 08:59 Jcrop.gif
> -rw-r--r-- 1 root root  2102 Jul 13 08:59 jquery.Jcrop-0.9.12.min.css
> -rw-r--r-- 1 root root 26141 Jul 13 08:59 jquery-ui-1.9.2.min.css
> 
> ./clipboard_image_paste/assets/stylesheets/images:
> insgesamt 72
> -rw-r--r-- 1 root root  180 Jul 13 08:59 ui-bg_flat_0_aaaaaa_40x100.png
> -rw-r--r-- 1 root root  178 Jul 13 08:59 ui-bg_flat_75_ffffff_40x100.png
> -rw-r--r-- 1 root root  120 Jul 13 08:59 ui-bg_glass_55_fbf9ee_1x400.png
> -rw-r--r-- 1 root root  105 Jul 13 08:59 ui-bg_glass_65_ffffff_1x400.png
> -rw-r--r-- 1 root root  111 Jul 13 08:59 ui-bg_glass_75_dadada_1x400.png
> -rw-r--r-- 1 root root  110 Jul 13 08:59 ui-bg_glass_75_e6e6e6_1x400.png
> -rw-r--r-- 1 root root  119 Jul 13 08:59 ui-bg_glass_95_fef1ec_1x400.png
> -rw-r--r-- 1 root root  101 Jul 13 08:59 ui-bg_highlight-soft_75_cccccc_1x100.png
> -rw-r--r-- 1 root root 4369 Jul 13 08:59 ui-icons_222222_256x240.png
> -rw-r--r-- 1 root root 4369 Jul 13 08:59 ui-icons_2e83ff_256x240.png
> -rw-r--r-- 1 root root 4369 Jul 13 08:59 ui-icons_454545_256x240.png
> -rw-r--r-- 1 root root 4369 Jul 13 08:59 ui-icons_888888_256x240.png
> -rw-r--r-- 1 root root 4369 Jul 13 08:59 ui-icons_cd0a0a_256x240.png
> 
> ./clipboard_image_paste/config:
> insgesamt 8
> drwxr-xr-x 2 root root 4096 Jul 13 08:57 locales
> -rw-r--r-- 1 root root    0 Jul 13 08:59 routes.rb
> -rw-r--r-- 1 root root  407 Jul 13 08:59 settings.yml
> 
> ./clipboard_image_paste/config/locales:
> insgesamt 64
> -rw-r--r-- 1 root root 1775 Jul 13 08:59 bg.yml
> -rw-r--r-- 1 root root 1206 Jul 13 08:59 cs.yml
> -rw-r--r-- 1 root root 1314 Jul 13 08:59 de.yml
> -rw-r--r-- 1 root root 1101 Jul 13 08:59 en.yml
> -rw-r--r-- 1 root root 1243 Jul 13 08:59 es.yml
> -rw-r--r-- 1 root root 1342 Jul 13 08:59 fr.yml
> -rw-r--r-- 1 root root 1204 Jul 13 08:59 it.yml
> -rw-r--r-- 1 root root 1344 Jul 13 08:59 ja.yml
> -rw-r--r-- 1 root root 1280 Jul 13 08:59 ko.yml
> -rw-r--r-- 1 root root 1221 Jul 13 08:59 pl.yml
> -rw-r--r-- 1 root root 1188 Jul 13 08:59 pt-BR.yml
> -rw-r--r-- 1 root root 1195 Jul 13 08:59 pt.yml
> -rw-r--r-- 1 root root 1693 Jul 13 08:59 ru.yml
> -rw-r--r-- 1 root root 1326 Jul 13 08:59 tr.yml
> -rw-r--r-- 1 root root  993 Jul 13 08:59 zh-TW.yml
> -rw-r--r-- 1 root root 1085 Jul 13 08:59 zh.yml
> 
> ./clipboard_image_paste/lib:
> insgesamt 4
> drwxr-xr-x 2 root root 4096 Jul 13 08:57 clipboard_image_paste
> 
> ./clipboard_image_paste/lib/clipboard_image_paste:
> insgesamt 8
> -rw-r--r-- 1 root root 3864 Jul 13 08:59 attachment_patch.rb
> -rw-r--r-- 1 root root  840 Jul 13 08:59 hooks.rb
> 
> ./clipboard_image_paste/suppl:
> insgesamt 112
> -rw-r--r-- 1 root root  9928 Jul 13 08:59 cbp_logo.png
> -rw-r--r-- 1 root root  4184 Jul 13 08:59 cbp-standalone-test.html
> -rw-r--r-- 1 root root 93637 Jul 13 08:59 jquery-1.8.3.min.js
>

**Comment by HandsomeRob2016** [comment]
Any idea?

**Comment by peclik** [comment]
Cannot replicate.
