### ISSUE TITLE
Redmine 3.3: "Add picture from clipboard" displayed at the bottom of on issue list and issue pages.

### ISSUE THREAD

**Issue by romanr** [peclik/clipboard_image_paste#61]
Redmine 3.3, clipboard_image_paste 1.10
"Add picture from clipboard (Maximum size: 9.88 MB)"
displayed at the bottom of on issue list and issue pages.

I tried all the different themes including default themes. It's same on all themes, appears at the bottom of pages.

anyone knows how to fix this?

**Comment by kozhurin** [comment]
On my Redmine 3.3.3 I had to create manually /public/plugin_assets/clipboard_image_paste folder and copy there folders from /plugins/clipboard_image_paste/assets to make it work properly.

**Comment by peclik** [comment]
Installation of 1.11 works flawlessly on Redmine 3.3 (Redmine need to be restarted after plugin files installation)
