### ISSUE TITLE
Compatibility with redmine_latex_mathjax

### ISSUE THREAD

**Issue by jwalkerbg** [peclik/clipboard_image_paste#63]
Now, 17.12.2016, clipboard_image_paste IS compatible with redmine_latex_mathjax 0.3.0
Tested in this environment:

Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [i386-mingw32]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.5
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.10
  redmine_code_review            0.7.0
  redmine_latex_mathjax_macro    0.3.0
  redmine_theme_changer          0.2.0
  sidebar_hide                   0.0.6

**Comment by peclik** [comment]
Thanks, removed from a list of incompatible plugins.
