### ISSUE TITLE
Issue with pasted images from another domain (CORS) + solution.

### ISSUE THREAD

**Issue by piejanssens** [peclik/clipboard_image_paste#64]
Problem: toDataURL doesn't work when the pasted image comes from copying an image from another domain.  "SecurityError: The operation is insecure"

**Comment by peclik** [comment]
Confirmed, but I don't know how to correct.
If possible, use PrintScreen instead of direct copy.

**Comment by aiovlev** [comment]
Hello. I have this problem too. Browser: Firefox Quantum 61.0.2.
