### ISSUE TITLE
Redmine 3.3 and 3.4 compatibility

### ISSUE THREAD

**Issue by eximius313** [peclik/clipboard_image_paste#65]
Do you plan to support Redmine 3.3 and 3.4?

**Comment by kinguru** [comment]
Please, make it compatible with Redmine 3.3

**Comment by smoolya17** [comment]
Requesting you to make it compatible with 3.3.2

**Comment by haskio** [comment]
is  support 3.3.3 or 3.4 now？

**Comment by archonwang** [comment]
support redmine 3.3.x
I used it well but with some minor bug.

**Comment by kozhurin** [comment]
It works well on my Redmine 3.3.3.
But I had to create manually /public/plugin_assets/clipboard_image_paste folder and copy there folders from /plugins/clipboard_image_paste/assets to make it work properly.

**Comment by peclik** [comment]
v1.12 compatible with Redmine 3.4.x

**Comment by eximius313** [comment]
Thank you!

**Comment by MensSana** [comment]
> It works well on my Redmine 3.3.3.
> But I had to create manually /public/plugin_assets/clipboard_image_paste folder and copy there folders from /plugins/clipboard_image_paste/assets to make it work properly.

Same here for 3.4.4.
