### ISSUE TITLE
RoutingError (No route matches [OPTIONS] "/plugin_assets/clipboard_image_paste/stylesheets"

### ISSUE THREAD

**Issue by bashforever** [peclik/clipboard_image_paste#66]
Hi!

We are on redmine 3.3. and using v1.10 of your plugin. It works great but usage throws in the redmine-logfile following error:
`ActionController::RoutingError (No route matches [OPTIONS] "/plugin_assets/clipboard_image_paste/stylesheets"):
  actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'`

(and so on). 

But nevertheless it works. The "stylesheets" folder is located in the subfolder "assets" (and not plugin_assets) and thus cannot be found by this route. 

Existing folder: _/opt/redmine/redmine/plugins/clipboard_image_paste/assets_

Is there any need or way to fix that? Can we simply rename "assets" to "plugin_assets" or does this break something else:

Thanks a lot

B4E

**Comment by kozhurin** [comment]
On my Redmine 3.3.3 I had to create manually /public/plugin_assets/clipboard_image_paste folder and copy there folders from /plugins/clipboard_image_paste/assets to make it work properly.

**Comment by peclik** [comment]
Installation of 1.11 works flawlessly on Redmine 3.3
