### ISSUE TITLE
Peer's certificate issuer has been marked as not trusted by the user.

### ISSUE THREAD

**Issue by cmozart** [peclik/clipboard_image_paste#68]
Has anyone ever experienced this?

-bash-4.2$ git clone https://github.com/peclik/clipboard_image_paste.git
Cloning into 'clipboard_image_paste'...
fatal: unable to access 'https://github.com/peclik/clipboard_image_paste.git/': Peer's certificate issuer has been marked as not trusted by the user.

Thanks in advance

**Comment by peclik** [comment]
Not plugin related.
