### ISSUE TITLE
Doesn't work with Firefox 54.0 (64-bit), Ubuntu 14.04

### ISSUE THREAD

**Issue by volontsevich** [peclik/clipboard_image_paste#69]
After pressing Ctrl+V nothing is happened, only this:
https://www.dropbox.com/s/nixpz8ydt1dlrxq/Screenshot_22.png?dl=0

Plugin version is 1.12, Redmine version is 3.3.0.stable

But all is OK with Chrome 59.0.3071.115 (Official Build) (64-bit) on the same Ubuntu 14.04

**Comment by mmohme** [comment]
Same problem with Firefox 54.0.1 on Win10 
Chrome is also fine on windows

Plugin version is 1.12, Redmine version is 3.4.2.stable.16828

**Comment by ilpssun** [comment]
Seems to be the same issue as in #77

**Comment by peclik** [comment]
Closing as duplicate of #77.
