### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by mandelli** [peclik/clipboard_image_paste#74]
The image captured are 32bit depth and PDF export does not support it, is it possible to configure bit depth?

**Comment by mandelli** [comment]
Seems in my Redmine Version (3.3.2) need to "Remove alpha channel from PNG image for Redmine"

**Comment by peclik** [comment]
Try to install Redmine with rmagick.
Without that, no image will appear in pdf exported.

**Comment by paulvi** [comment]
@mandelli Please rename issue to "image 32bit depth" or close if suggested did work.
